spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:excellent-book}?serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
application:
  bucket:
    name: spring-lab-test
cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      accessKey: AKIAWJF7EP7ZE6AAIG5Z
      secretKey: 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
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000