spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:excellent-book}?serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
application:
  bucket:
    name: spring-lab-test
cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      accessKey:
      secretKey:
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000
  base-path: /api/v1

novaPoshta:
  server:
    address: https://api.novaposhta.ua/v2.0/json/
  apiKey: